In [62]:
import datetime
import numpy as np

In [2]:
dt_now = datetime.datetime.now()

In [4]:
dt_now.day

9

In [5]:
num_element = 10

In [6]:
2*np.pi*np.random.rand(num_element)

array([2.64120273, 5.00590228, 3.12294399, 3.62378888, 1.01993952,
       2.59977548, 3.80203096, 2.98508792, 6.05666924, 5.35706225])

In [7]:
np.random.rand(num_element)

array([0.83286748, 0.13570982, 0.40143822, 0.93800203, 0.95292645,
       0.18410197, 0.08811886, 0.97689274, 0.76301591, 0.25254795])

In [9]:
np.random.rand()

0.27032951391679005

In [25]:
np.random.normal(
    loc   = 1,      # 平均
    scale = 0.1,      # 標準偏差
)

0.9282176735039769

In [34]:
input_data = np.zeros([1,6*num_element])

In [40]:
input_data[0][:5] = np.full(5,3)

In [39]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [45]:
input_data[0,4:10]

array([3., 0., 0., 0., 0., 0.])

In [71]:
from multiprocessing import Pool, Lock, Value
import time
import pandas as pd

KeyboardInterrupt: 

In [ ]:
def mainf():
    l.acquire()
    if count.value %2==0:
        with iter.get_lock():
            iter.value = iter.value+1 
    l.release()
    count.value+=1
    print(f'iter:{iter.value}')
    print(f'count:{count.value}')
    return iter.value

In [ ]:
if __name__ == '__main__':
    start = time.time()
    date = datetime.datetime.now()
    l = Lock() 
    iter = Value('i',0) 
    count = Value('i',0)
    print("Calculating...")
    p = Pool(processes=12)
    a = list(range(5))
    b = list(range(5))
    np.random.shuffle(b)
    result_list = p.starmap(func=mainf, iterable=zip(a,b))
    p.close()
    total_time = time.time()-start
    total_time = datetime.timedelta(seconds=total_time)

In [57]:
a = list(range(5))
b = list(range(5))

In [58]:
np.random.shuffle(b)

In [59]:
a

[0, 1, 2, 3, 4]

In [60]:
b

[1, 4, 0, 3, 2]

In [63]:
target = np.zeros([1,60])

In [66]:
target[0][:20] =np.full(20,3)

In [72]:
import pandas as pd

In [73]:
pd.DataFrame(np.array(target[0][:20]))

0
0   3.0
1   3.0
2   3.0
3   3.0
4   3.0
5   3.0
6   3.0
7   3.0
8   3.0
9   3.0
10  3.0
11  3.0
12  3.0
13  3.0
14  3.0
15  3.0
16  3.0
17  3.0
18  3.0
19  3.0